name: build and release chuckya-fe and akkoma-fe

on:
  schedule:
    - cron:
        "00 06 * * *"
  push:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: |
          mkdir -p $HOME/.local/bin
          corepack enable --install-directory $HOME/.local/bin

      - name: compile masto-fe
        run: |
          git clone https://forged.synth.download/synth.download/Chuckya-fe-standalone.git

      - name: compile akkoma-fe
        run: |
          git clone https://forged.synth.download/synth.download/akkoma-fe.git

      - id: tag_name
        run: echo ::set-output name=tag_name::$(date +%Y.%m.%d).$(git rev-parse --short HEAD)

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          make_latest: true
          files: |
            masto-fe.zip
            akkoma-fe.zip