name: build and release akkoma-fe

on:
  schedule:
    - cron:
        "00 06 * * *"
  push:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: |
          mkdir -p $HOME/.local/bin
          corepack enable --install-directory $HOME/.local/bin

      - name: compile akkoma-fe
        run: |
          git clone https://forged.synth.download/sd/akkoma-fe.git && cd akkoma-fe
          export COREPACK_ENABLE_DOWNLOAD_PROMPT=0 && npx --yes update-browserslist-db@latest && $HOME/.local/bin/yarn && $HOME/.local/bin/yarn build
          cd dist && zip -r ../../akkoma-fe.zip .

      - id: tag_name
        run: echo ::set-output name=tag_name::$(date +%Y.%m.%d).$(git rev-parse --short HEAD)

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          make_latest: true
          files: akkoma-fe.zip
