name: build and release akkoma-fe for iceshrimp

on:
  schedule:
    - cron:
        "00 06 * * *"
  push:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: |
          mkdir -p $HOME/.local/bin
          corepack enable --install-directory $HOME/.local/bin

      - name: install python
        run: |
          sudo apt update
          sudo apt install python3 python3-requests

      - name: compile akkoma-fe
        run: |
          git clone https://forged.synth.download/sd/akkoma-fe-iceshrimp.git && cd akkoma-fe-iceshrimp
          cd tools && python3 download_ruffle.py && cd ../
          export COREPACK_ENABLE_DOWNLOAD_PROMPT=0 && npx --yes update-browserslist-db@latest && $HOME/.local/bin/yarn && $HOME/.local/bin/yarn build
          cd dist && zip -r ../../akkoma-fe-iceshrimp.zip .

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: fedi-frontend
          make_latest: true
          files: akkoma-fe-iceshrimp.zip
